"""키워드 기반 신규 종목 발견 힌트 사전.

뉴스 헤드라인/요약을 스캔해 현재 추적 유니버스에 없는 종목이
자주 언급되면 대시보드에 '추가 고려' 알림을 띄운다.
키워드는 소문자 부분 일치(in)로 검색한다.
"""
from __future__ import annotations

# symbol → (표시 이름, 검색 키워드 목록)
US_HINTS: dict[str, tuple[str, list[str]]] = {
    "META":   ("Meta",             ["meta platforms", " meta ", "facebook"]),
    "NFLX":   ("Netflix",          ["netflix"]),
    "AMD":    ("AMD",              ["amd ", "advanced micro devices"]),
    "INTC":   ("Intel",            ["intel "]),
    "QCOM":   ("Qualcomm",         ["qualcomm"]),
    "CRM":    ("Salesforce",       ["salesforce"]),
    "ORCL":   ("Oracle",           ["oracle "]),
    "PLTR":   ("Palantir",         ["palantir"]),
    "SNOW":   ("Snowflake",        ["snowflake"]),
    "ARM":    ("ARM Holdings",     ["arm holdings", "arm chips", "arm ltd"]),
    "SMCI":   ("Super Micro",      ["super micro", "supermicro"]),
    "PANW":   ("Palo Alto",        ["palo alto networks"]),
    "CRWD":   ("CrowdStrike",      ["crowdstrike"]),
    "COIN":   ("Coinbase",         ["coinbase"]),
    "MSTR":   ("MicroStrategy",    ["microstrategy"]),
    "UBER":   ("Uber",             ["uber "]),
    "SHOP":   ("Shopify",          ["shopify"]),
    "SPOT":   ("Spotify",          ["spotify"]),
    "GS":     ("Goldman Sachs",    ["goldman sachs"]),
    "BAC":    ("Bank of America",  ["bank of america"]),
    "WMT":    ("Walmart",          ["walmart"]),
    "V":      ("Visa",             ["visa "]),
    "MA":     ("Mastercard",       ["mastercard"]),
    "UNH":    ("UnitedHealth",     ["unitedhealth"]),
    "PFE":    ("Pfizer",           ["pfizer"]),
    "JNJ":    ("J&J",              ["johnson & johnson", "j&j"]),
    "DIS":    ("Disney",           ["disney"]),
    "BA":     ("Boeing",           ["boeing"]),
    "NEM":    ("Newmont",          ["newmont"]),
    "BHP":    ("BHP Group",        ["bhp "]),
    "RIO":    ("Rio Tinto",        ["rio tinto"]),
    "VALE":   ("Vale",             ["vale sa", "vale mining"]),
    "OXY":    ("Occidental",       ["occidental petroleum"]),
    "CVX":    ("Chevron",          ["chevron"]),
    "HAL":    ("Halliburton",      ["halliburton"]),
    "SLB":    ("Schlumberger",     ["schlumberger", "slb "]),
    "MOS":    ("Mosaic",           ["mosaic company"]),
    "CF":     ("CF Industries",    ["cf industries"]),
    "AA":     ("Alcoa",            ["alcoa"]),
}

KR_HINTS: dict[str, tuple[str, list[str]]] = {
    "000270.KS": ("기아",              ["기아차", "기아자동차", " 기아 "]),
    "207940.KS": ("삼성바이오로직스",  ["삼성바이오"]),
    "051910.KS": ("LG화학",            ["lg화학", "엘지화학"]),
    "066570.KS": ("LG전자",            ["lg전자", "엘지전자"]),
    "003550.KS": ("LG",                ["lg그룹"]),
    "096770.KS": ("SK이노베이션",      ["sk이노베이션"]),
    "028260.KS": ("삼성물산",          ["삼성물산"]),
    "009150.KS": ("삼성전기",          ["삼성전기"]),
    "012330.KS": ("현대모비스",        ["현대모비스"]),
    "086790.KS": ("하나금융지주",      ["하나금융", "하나은행"]),
    "055550.KS": ("신한지주",          ["신한금융", "신한은행"]),
    "316140.KS": ("우리금융지주",      ["우리금융", "우리은행"]),
    "030200.KS": ("KT",                ["kt ", " kt\n"]),
    "017670.KS": ("SK텔레콤",          ["sk텔레콤", "skt "]),
    "036570.KS": ("엔씨소프트",        ["엔씨소프트", "nc소프트"]),
    "259960.KS": ("크래프톤",          ["크래프톤", "배틀그라운드"]),
    "041510.KS": ("에스엠엔터",        ["sm엔터", "에스엠엔터"]),
    "035900.KS": ("JYP엔터",           ["jyp엔터", "제이와이피"]),
    "122870.KS": ("YG엔터",            ["yg엔터", "와이지엔터"]),
    "247540.KS": ("에코프로비엠",      ["에코프로비엠"]),
    "086520.KS": ("에코프로",          ["에코프로 "]),
    "006400.KS": ("삼성SDI",           ["삼성sdi"]),
    "011200.KS": ("HMM",               ["hmm ", "현대상선"]),
    "326030.KS": ("SK바이오팜",        ["sk바이오팜"]),
    "091990.KS": ("셀트리온헬스케어",  ["셀트리온헬스케어"]),
    "251270.KS": ("넷마블",            ["넷마블"]),
    "032830.KS": ("삼성생명",          ["삼성생명"]),
}
